### ISSUE TITLE
tailoring file?

### ISSUE THREAD

**Issue by mtward** [theforeman/foreman_scap_client#14]
Would it be possible to reference a tailoring file in the config so something like this could be run?

oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_rht-ccp_tailored --tailoring-file tailored-rhel6.xml

**Comment by ares** [comment]
I think that calling oscap like this would be easy change, the hard part is distributing the tailoring file. Would you like to upload them through Foreman? How would you like to apply them, per host/host group or something else like OS/domain/...? Could you please open this issue on our issue tracker - http://projects.theforeman.org/projects/openscap/issues you'll need to register but you can use github account for that.

**Comment by mtward** [comment]
sure - opening an issue there.
