### ISSUE TITLE
Fail to Run scan RHEL7

### ISSUE THREAD

**Issue by naresh777** [theforeman/foreman_scap_client#15]
Fail to Run the scan and throws this error. given all details in configuration file 

 foreman_scap_client 1
/usr/share/gems/gems/foreman_scap_client-0.1.2/lib/foreman_scap_client/client.rb:121:in `ensure_scan_file': undefined method`[]' for nil:NilClass (NoMethodError)
        from /usr/share/gems/gems/foreman_scap_client-0.1.2/lib/foreman_scap_client/client.rb:14:in `run'
        from /usr/share/gems/gems/foreman_scap_client-0.1.2/bin/foreman_scap_client:9:in`<top (required)>'
        from /bin/foreman_scap_client:23:in `load'
        from /bin/foreman_scap_client:23:in`<main>'

**Comment by shlomizadok** [comment]
It seems that config file is missing
Can you share some more details?

**Comment by naresh777** [comment]
Thanks for quick response and Sorry for delay.I copied the config file from sample. My config file at /etc/foreman_scap_client/config.yaml Looks like below.

```
# Foreman proxy to which reports should be uploaded
:server: 'XXXXXX.YYYY.com'
:port: 8443

# SSL specific options
:ca_file: '/var/lib/puppet/ssl/certs/ca.pem'
# this client certificate, usually the same that puppet agent use
:host_certificate: '/var/lib/puppet/ssl/certs/XXXXX.YYYY.com.pem'
# this client private key, usually the same that puppet agent use
:host_private_key: '/var/lib/puppet/ssl/private_keys/XXXX.YYYY.com.pem'

# policy (key is id as in Foreman)
1:
  # which profile should be run on this client (use profile id)
  # you can find out the profile id from ds file by running oscap info name-ds.xml
  # leave empty for default profile
  :profile: ''
  # ds input file
  :content_path: '/usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml'

2:
  :profile: 'xccdf_org.ssgproject.content_profile_common'
  :content_path: '/usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml'
```

**Comment by shlomizadok** [comment]
Hey,
Thanks.
The problem is that policy id: 1 has no profile.
I am assuming that running `foreman_scap_client 2` works well

I see the problem now. :cry: 
Can you please open a new issue on http://projects.theforeman.org/projects/foreman_openscap/issues and I will try to fix this asap.

As a workaround add the default XCCDF profile to policy 1
so it would look like:

``` yaml
1:
  # which profile should be run on this client (use profile id)
  # you can find out the profile id from ds file by running oscap info name-ds.xml
  # leave empty for default profile
  :profile: 'xccdf_org.ssgproject.content_profile_common'
  # ds input file
  :content_path: '/usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml'
```

Thanks!

**Comment by ares** [comment]
I suppose this have been fixed, if not, please reopen, ideally in the official bug trtacker at http://projects.theforeman.org/projects/foreman_openscap/issues thank you
