### ISSUE TITLE
Support online remediation

### ISSUE THREAD

**Issue by fftux** [theforeman/foreman_scap_client#20]
Support for online remediation here would lay the foundation for remediation from foreman.  This could be a achieved by adding a boolean variable that could be used to control the addition of --remediate on the oscap command.

Of course, this would consequently lead to the need for an update to the 'puppet-foreman_scap_client' project to support these changes.

**Comment by ares** [comment]
We were considerimg using remote execution plugin, since we thought user wants to remediate asap. Also it has load distribution capabilities built-in. Would that make sense?

**Comment by fftux** [comment]
That seems reasonable.  Would be great if this was developed in such a way that an administrator could be selective in what findings they want to remediate, instead of having to do all as well.  Ideally, they would be scanning with a customized scap profile to avoid this, but we know that is not always the case.

**Comment by ares** [comment]
It depends on what openscap can provide. If we get remediation scripts broken down per failed rules, then it's definitely doable. Anyway, let's move the discussion and requirements specifications to existing RFE in our issue tracker at http://projects.theforeman.org/issues/12292

Closing this one.
