### ISSUE TITLE
Autoguess the paths to the certs/pems

### ISSUE THREAD

**Issue by isimluk** [theforeman/foreman_scap_client#3]
Most common scenario would be to re-use puppet certificate infrastructure. Perhaps we can automagically autoguess usual path to the certificates.

Currently, when config does not contain paths we get:

```
[root@fedora20 tmp]# /usr/bin/foreman_scap_client 1
DEBUG: running: oscap xccdf eval  --results-arf /tmp/d20150120-23771-1komslx/results.xml /usr/share/xml/scap/ssg/fedora/ssg-fedora-ds.xml
Uploading results to https://foreman.local.lan:8443/compliance/arf/1
Unable to load certs
no implicit conversion of nil into String
```

**Comment by shlomizadok** [comment]
Maybe when puppet updates the config, it should update it with its certs?

**Comment by ares** [comment]
it should already do, based on [default value](https://github.com/OpenSCAP/puppet-foreman_scap_client/blob/master/manifests/init.pp#L34) and [template](https://github.com/OpenSCAP/puppet-foreman_scap_client/blob/master/templates/config.yaml.erb#L11)

**Comment by ares** [comment]
@isimluk can you check `host_certificate` and `host_private_key` values in you client config file?

**Comment by isimluk** [comment]
Yeah, the puppet-foreman_scap_client is pushing good defaults here. The question here is whether the foreman_scap_client should do the auto-guessing.

**Comment by ares** [comment]
Do you want to make this part of policy wizard? Or how would you like to get better source of information? Parsing puppet config file is not a good option since users may choose other certificates? And they can override the value in Foreman now.

**Comment by isimluk** [comment]
I was thinking about taking the certificate from puppet. Like the `puppet --configprint all` does.

But it is perhaps an unnecessary burden at this point of time. Feel free to close, if you don't want such ability.

**Comment by ares** [comment]
I'd keep it open for now. We'll hear from users what's most wanted way I guess.

**Comment by shlomizadok** [comment]
related to https://github.com/OpenSCAP/puppet-foreman_scap_client/pull/6 ?

**Comment by isimluk** [comment]
no

**Comment by ares** [comment]
seems like there was not enough interest, closing, please reopen if you disagree
