### ISSUE TITLE
Failure to install foreman_scap_client due to ncurses

### ISSUE THREAD

**Issue by boydhako** [theforeman/foreman_scap_client#34]
Also posted in Foreman forums @ https://community.theforeman.org/t/cant-install-foreman-scap-client/21836

Issue is due needing an older version of ncurses to install.

[root@localhost bha]# yum info rubygem-foreman_scap_client
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Available Packages
Name        : rubygem-foreman_scap_client
Arch        : noarch
Version     : 0.4.6
Release     : 1.el7sat
Size        : 22 k
Repo        : rhel-7-server-satellite-tools-6.7-rpms/x86_64
Summary     : Client script that runs OpenSCAP scan and uploads the result
to foreman proxy
URL         : https://github.com/openscap/foreman_scap_client
License     : GPLv3
Description : Client script that runs OpenSCAP scan and uploads the result
to foreman proxy.

---> Package pcre.i686 0:8.32-12.el7 will be installed
--> Finished Dependency Resolution
--> Finding unneeded leftover dependencies
Found and removing 0 unneeded dependencies
Error: Package: ncurses-libs-5.9-13.20130511.el7.i686 (rhel-7-server-rpms)
          Requires: ncurses-base = 5.9-13.20130511.el7
          Installed: ncurses-base-5.9-14.20130511.el7_4.noarch
(@rhel-7-server-rpms)
              ncurses-base = 5.9-14.20130511.el7_4
          Available: ncurses-base-5.9-13.20130511.el7.noarch
(rhel-7-server-rpms)
              ncurses-base = 5.9-13.20130511.el7
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest

**Comment by xprazak2** [comment]
Closing as foreman_scap_client does not depend on ncurses, this seems like some sort of package clash on target system. We can continue the discussion on the community forum.Thanks!
